In [67]:
import pandas as pd
import numpy as np

In [68]:
df=pd.read_csv('등급별예측데이터.csv',encoding="cp949")
df.head(5)

,읍면동,시장성,성장성,개폐업안정성,경쟁도,유동인구 시장성,거주인구시장성,업종소분류,20대직장인구 22년상반기 평균소득,20대직장인구 22년하반기 평균소득,...,50대직장인구 22년상반기 평균소득,50대직장인구 22년하반기 평균소득,50대직장인구 22년상반기 평균소비,50대직장인구 22년하반기 평균소비,60대 이상직장인구 22년상반기 평균소득,60대 이상직장인구 22년하반기 평균소득,60대 이상직장인구 22년상반기 평균소비,60대 이상직장인구 22년하반기 평균소비,직장인구수,창업성공등급
0,왕정동,63.8,100.0,0.0,100.0,6.5,5.3,기타일반음식,217,221,...,374,380,229,244,304,304,142,151,5741,A
1,무주읍,27.1,76.5,0.0,100.0,29.1,39.7,농축수산물,246,246,...,383,390,222,222,294,295,146,145,2240,A
2,수송동,71.0,63.0,0.0,100.0,12.2,20.7,한약방,220,230,...,365,373,204,225,298,299,158,145,192,A
3,임실읍,30.0,87.0,0.0,100.0,21.0,27.4,조경/화원,254,262,...,407,412,237,240,323,339,143,154,2362,A
4,호성동,47.6,100.0,0.0,100.0,4.1,6.2,농축수산물,238,242,...,395,401,245,254,315,319,164,174,3997,A

In [69]:
df.columns

Index(['읍면동', '시장성', '성장성', '개폐업안정성', '경쟁도', '유동인구 시장성', '거주인구시장성', '업종소분류',
       '20대직장인구 22년상반기 평균소득', '20대직장인구 22년하반기 평균소득', '20대직장인구 22년상반기 평균소비',
       '20대직장인구 22년하반기 평균소비', '30대직장인구 22년상반기 평균소득', '30대직장인구 22년하반기 평균소득',
       '30대직장인구 22년상반기 평균소비', '30대직장인구 22년하반기 평균소비', '40대직장인구 22년상반기 평균소득',
       '40대직장인구 22년하반기 평균소득', '40대직장인구 22년상반기 평균소비', '40대직장인구 22년하반기 평균소비',
       '50대직장인구 22년상반기 평균소득', '50대직장인구 22년하반기 평균소득', '50대직장인구 22년상반기 평균소비',
       '50대직장인구 22년하반기 평균소비', '60대 이상직장인구 22년상반기 평균소득',
       '60대 이상직장인구 22년하반기 평균소득', '60대 이상직장인구 22년상반기 평균소비',
       '60대 이상직장인구 22년하반기 평균소비', '직장인구수', '창업성공등급'],
      dtype='object')

In [70]:
df.dtypes

읍면동                        object
시장성                       float64
성장성                       float64
개폐업안정성                    float64
경쟁도                       float64
유동인구 시장성                  float64
거주인구시장성                   float64
업종소분류                      object
20대직장인구 22년상반기 평균소득         int64
20대직장인구 22년하반기 평균소득         int64
20대직장인구 22년상반기 평균소비         int64
20대직장인구 22년하반기 평균소비         int64
30대직장인구 22년상반기 평균소득         int64
30대직장인구 22년하반기 평균소득         int64
30대직장인구 22년상반기 평균소비         int64
30대직장인구 22년하반기 평균소비         int64
40대직장인구 22년상반기 평균소득         int64
40대직장인구 22년하반기 평균소득         int64
40대직장인구 22년상반기 평균소비         int64
40대직장인구 22년하반기 평균소비         int64
50대직장인구 22년상반기 평균소득         int64
50대직장인구 22년하반기 평균소득         int64
50대직장인구 22년상반기 평균소비         int64
50대직장인구 22년하반기 평균소비         int64
60대 이상직장인구 22년상반기 평균소득      int64
60대 이상직장인구 22년하반기 평균소득      int64
60대 이상직장인구 22년상반기 평균소비      int64
60대 이상직장인구 22년하반기 평균소비      int64
직장인구수                       int64
창업성공등급                     object
dtype: object

In [71]:
# 숫자형 변수
num = df.select_dtypes(include=['int64', 'float64'])

# 범주형 변수
cat = df.select_dtypes(include=['object', 'category'])

In [72]:
cat = cat.drop('창업성공등급', axis = 1) # 종속 변수 제외

In [73]:
num

,시장성,성장성,개폐업안정성,경쟁도,유동인구 시장성,거주인구시장성,20대직장인구 22년상반기 평균소득,20대직장인구 22년하반기 평균소득,20대직장인구 22년상반기 평균소비,20대직장인구 22년하반기 평균소비,...,40대직장인구 22년하반기 평균소비,50대직장인구 22년상반기 평균소득,50대직장인구 22년하반기 평균소득,50대직장인구 22년상반기 평균소비,50대직장인구 22년하반기 평균소비,60대 이상직장인구 22년상반기 평균소득,60대 이상직장인구 22년하반기 평균소득,60대 이상직장인구 22년상반기 평균소비,60대 이상직장인구 22년하반기 평균소비,직장인구수
0,63.8,100.0,0.0,100.0,6.5,5.3,217,221,117,120,...,263,374,380,229,244,304,304,142,151,5741
1,27.1,76.5,0.0,100.0,29.1,39.7,246,246,158,169,...,251,383,390,222,222,294,295,146,145,2240
2,71.0,63.0,0.0,100.0,12.2,20.7,220,230,138,153,...,268,365,373,204,225,298,299,158,145,192
3,30.0,87.0,0.0,100.0,21.0,27.4,254,262,171,166,...,250,407,412,237,240,323,339,143,154,2362
4,47.6,100.0,0.0,100.0,4.1,6.2,238,242,148,145,...,298,395,401,245,254,315,319,164,174,3997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9058,0.0,2.5,0.0,0.0,1.4,0.8,228,237,146,155,...,222,348,356,181,193,307,312,134,182,179
9059,0.0,1.0,0.0,0.0,1.3,1.7,243,259,179,167,...,284,445,448,232,251,376,395,166,171,392
9060,0.0,1.5,0.0,0.0,0.9,1.3,235,242,192,161,...,259,380,388,214,231,278,278,208,189,230
9061,0.0,1.0,0.0,0.0,1.1,1.6,233,241,164,166,...,287,364,371,235,243,287,291,151,156,23456
9062,0.0,1.0,0.0,0.0,1.0,0.8,246,274,184,227,...,292,365,366,229,229,297,298,178,157,228

In [75]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()
num_scaled = scaler.fit_transform(num)
num_df_scaled=pd.DataFrame(data=num_scaled, columns=num.columns)
num_df_scaled

,시장성,성장성,개폐업안정성,경쟁도,유동인구 시장성,거주인구시장성,20대직장인구 22년상반기 평균소득,20대직장인구 22년하반기 평균소득,20대직장인구 22년상반기 평균소비,20대직장인구 22년하반기 평균소비,...,40대직장인구 22년하반기 평균소비,50대직장인구 22년상반기 평균소득,50대직장인구 22년하반기 평균소득,50대직장인구 22년상반기 평균소비,50대직장인구 22년하반기 평균소비,60대 이상직장인구 22년상반기 평균소득,60대 이상직장인구 22년하반기 평균소득,60대 이상직장인구 22년상반기 평균소비,60대 이상직장인구 22년하반기 평균소비,직장인구수
0,63.8,1.534772,0.0,100.0,0.140845,-0.051282,-1.266667,-1.3750,-2.333333,-2.222222,...,-0.814815,-0.739130,-0.518519,-0.823529,-0.333333,-0.178571,-0.28,-0.941176,-0.526316,-0.273311
1,27.1,0.971223,0.0,100.0,3.323944,4.358974,0.666667,0.1875,-0.055556,0.500000,...,-1.259259,-0.347826,-0.148148,-1.235294,-1.380952,-0.535714,-0.64,-0.705882,-0.842105,-0.446311
2,71.0,0.647482,0.0,100.0,0.943662,1.923077,-1.066667,-0.8125,-1.166667,-0.388889,...,-0.629630,-1.130435,-0.777778,-2.294118,-1.238095,-0.392857,-0.48,0.000000,-0.842105,-0.547512
3,30.0,1.223022,0.0,100.0,2.183099,2.782051,1.200000,1.1875,0.666667,0.333333,...,-1.296296,0.695652,0.666667,-0.352941,-0.523810,0.500000,1.12,-0.882353,-0.368421,-0.440283
4,47.6,1.534772,0.0,100.0,-0.197183,0.064103,0.133333,-0.0625,-0.611111,-0.833333,...,0.481481,0.173913,0.259259,0.117647,0.142857,0.214286,0.32,0.352941,0.684211,-0.359490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9058,0.0,-0.803357,0.0,0.0,-0.577465,-0.628205,-0.533333,-0.3750,-0.722222,-0.277778,...,-2.333333,-1.869565,-1.407407,-3.647059,-2.761905,-0.071429,0.04,-1.411765,1.105263,-0.548154
9059,0.0,-0.839329,0.0,0.0,-0.591549,-0.512821,0.466667,1.0000,1.111111,0.388889,...,-0.037037,2.347826,2.000000,-0.647059,0.000000,2.392857,3.36,0.470588,0.526316,-0.537629
9060,0.0,-0.827338,0.0,0.0,-0.647887,-0.564103,-0.066667,-0.0625,1.833333,0.055556,...,-0.962963,-0.478261,-0.222222,-1.705882,-0.952381,-1.107143,-1.32,2.941176,1.473684,-0.545634
9061,0.0,-0.839329,0.0,0.0,-0.619718,-0.525641,-0.200000,-0.1250,0.277778,0.333333,...,0.074074,-1.173913,-0.851852,-0.470588,-0.380952,-0.785714,-0.80,-0.411765,-0.263158,0.602066
9062,0.0,-0.839329,0.0,0.0,-0.633803,-0.628205,0.666667,1.9375,1.388889,3.722222,...,0.259259,-1.130435,-1.037037,-0.823529,-1.047619,-0.428571,-0.52,1.176471,-0.210526,-0.545733

In [76]:
cat_dummies=pd.get_dummies(cat).astype(np.float32)
cat_dummies

,읍면동_감곡면,읍면동_강진면,읍면동_개정동,읍면동_개정면,읍면동_검산동,읍면동_경암동,읍면동_경천면,읍면동_계남면,읍면동_계북면,읍면동_계화면,...,업종소분류_한의원/한방병원,업종소분류_할인점,업종소분류_호텔(1급/2급/관광),업종소분류_호프/소주,업종소분류_화랑,업종소분류_화물운송/이사,업종소분류_화방(표구),업종소분류_화장품,업종소분류_회계/세무/관세/변리,업종소분류_ＰＣ방
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9058,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9059,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9060,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
9061,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9062,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [77]:
a=df[['창업성공등급']]

In [78]:
comp=pd.concat([a, num_df_scaled, cat_dummies],axis=1)
comp

,창업성공등급,시장성,성장성,개폐업안정성,경쟁도,유동인구 시장성,거주인구시장성,20대직장인구 22년상반기 평균소득,20대직장인구 22년하반기 평균소득,20대직장인구 22년상반기 평균소비,...,업종소분류_한의원/한방병원,업종소분류_할인점,업종소분류_호텔(1급/2급/관광),업종소분류_호프/소주,업종소분류_화랑,업종소분류_화물운송/이사,업종소분류_화방(표구),업종소분류_화장품,업종소분류_회계/세무/관세/변리,업종소분류_ＰＣ방
0,A,63.8,1.534772,0.0,100.0,0.140845,-0.051282,-1.266667,-1.3750,-2.333333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,A,27.1,0.971223,0.0,100.0,3.323944,4.358974,0.666667,0.1875,-0.055556,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,A,71.0,0.647482,0.0,100.0,0.943662,1.923077,-1.066667,-0.8125,-1.166667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,A,30.0,1.223022,0.0,100.0,2.183099,2.782051,1.200000,1.1875,0.666667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,A,47.6,1.534772,0.0,100.0,-0.197183,0.064103,0.133333,-0.0625,-0.611111,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9058,E,0.0,-0.803357,0.0,0.0,-0.577465,-0.628205,-0.533333,-0.3750,-0.722222,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9059,E,0.0,-0.839329,0.0,0.0,-0.591549,-0.512821,0.466667,1.0000,1.111111,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9060,E,0.0,-0.827338,0.0,0.0,-0.647887,-0.564103,-0.066667,-0.0625,1.833333,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
9061,E,0.0,-0.839329,0.0,0.0,-0.619718,-0.525641,-0.200000,-0.1250,0.277778,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9062,E,0.0,-0.839329,0.0,0.0,-0.633803,-0.628205,0.666667,1.9375,1.388889,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [79]:
#comp.to_csv('comp.csv',encoding='cp949',index = False)